attire = "bow tie" / "necktie" / "Internet attire"
attireBlock = (
    "bow tie" /
    "necktie" /
    "Internet attire"
)
attireGroup = (
    attire //
    attireBlock
)
protocol = 6 / 17

address = { delivery }

delivery = (
    street: tstr,
    ?number: uint,
    city // po-box: uint,
    city // foo: tstr / uint // foobar // per-pickup: true
)

city = (
    name: tstr,
    zip-code: uint
)

attire /= "swimwear"

delivery //= (
    lat: float, long: float, drone-type: tstr
)