person = {
    identity,                         ; an identity
    employer: tstr,                   ; some employer
}

dog = {
    identity,                         ; an identity again
    leash-length: float,              ; some length
}

identity = (
    age: int,                         ; an age
    name: tstr,                       ; a name
)

Geography = [
    city           : tstr,            ; a city
    gpsCoordinates : GpsCoordinates,  ; some coordinates
]

GpsCoordinates = {
    longitude      : uint,            ; degrees, scaled by 10^7
    latitude       : uint,            ; degreed, scaled by 10^7
}

located-samples = {
    "sample-point" => int,            ; some
    "samples" => [+ float],           ; comments
}

extensible-map-example = {
    ? "optional-key" ^ => int,        ; some
    ? "optional-key2": int,           ; really
    ? optional-key3: int,             ; interesting
    * tstr => any                     ; comments
}

personWithoutComment = {
    identity,
    employer: tstr,
}

dogWithoutComment = {
    identity,
    leash-length: float,
}

identityWithoutComment = (
    age: int,
    name: tstr,
)

GeographyWithoutComment = [
    city           : tstr,
    gpsCoordinates : GpsCoordinates,
]

GpsCoordinatesWithoutComment = {
    longitude      : uint,
    latitude       : uint,
}

located-samples-without-comments = {
    "sample-point" => int,
    "samples" => [+ float],
}

extensible-map-example-without-comments = {
    ? "optional-key" ^ => int,
    ? "optional-key2": int,
    ? optional-key3: int,
    * tstr => any
}