Example = {
   title: tstr,                                 ; summary of test
   ? description: tstr,                         ; longer description of test
   ? fail : bool,                               ; Is this a success or failure test
   "input": Inputs,                             ; Inputs to create the test
   ? intermediates : Intermediates,             ; Intermediate values for debugging
   output: Outputs,                             ; Outputs of the test
   attire: "bow tie",
   someBool: true,
   someOtherBool: false,
   count: 123,
   negative-count: -123,
   ?"rating": 0.5724646875815566,
   hexa: 0x123,
   bin: 0b123, 
   foobar,
   samples: [+ float],
   multitype: float / tstr / "foobar",
   my_uri: #6.32(tstr) / tstr,
}