ip4 = bstr .size 4
label = bstr .size (1..63)
nai = tstr .regexp "[A-Za-z0-9]+@[A-Za-z0-9]+(\\.[A-Za-z0-9]+)+"
rwxbits = uint .bits rwx

foo = ip4 .and nai
fooWithin = ip4 .within nai
bar = foo .ne fooWithin

speed = number .ge 0  ; unit: m/s
speed2 = number .le 10  ; unit: m/s
speed3 = number .gt 0  ; unit: m/s
speed4 = number .lt 10  ; unit: m/s

displayed-step = number .default 1
someGroup = {
    ? optional: tstr .default "foobar"
}