device-address = byte
max-byte = 255 / float / int
my_uri = #6.32(tstr) / tstr
byte = 0..max-byte
first-non-byte = 256
byte1 = 0...first-non-byte
min..max = 0
byte2 = min..max...first-non-byte
byte3 = min..max ... first-non-byte
js-int = -9007199254740991..9007199254740991
scale = 0.1..2.0 .default 1.0
