Message = (
  CommandResponse //
  ErrorResponse //
  Event
)

ErrorCode = ("invalid argument" /
             "invalid session id" /
             "no such alert" /
             "no such frame" /
             "no such handle" /
             "no such node" /
             "no such script" /
             "session not created" /
             "unknown command" /
             "unknown error" /
             "unsupported operation")
