name: NPM Publish

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release type - major, minor or patch'
        required: true
        default: 'patch'
      distTag:
        description: 'NPM tag (e.g. use "next" to release a test version)'
        required: true
        default: 'latest'

env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install Dependencies
        run: npm ci
      - name: Unit Tests
        run: npm run test
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Setup Node version
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/
      - name: Setup Git
        run: |
          git config --global user.name "christian-bromann"
          git config --global user.email "git@bromann.dev"
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: npm run build
        env:
          NODE_ENV: production
      - name: Release
        run: npm run release:ci -- ${{github.event.inputs.releaseType}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}